In [80]:
import os 
import pandas as pd 
import numpy as np 
os.chdir('/mnt/BioHome/jreyna/jreyna/projects/cmi-pb-preds/')

In [81]:
assays = ('cytof', 'olink', 'rnaseq')
longnames = ('live_cell_percentages', 'olink_prot_exp', 'rnaseq')

In [119]:
########################################################################
# Load the 2021 data ###############################################
########################################################################

In [138]:
twentyone_data = {}

# get meta master table
for metatable in ('subject', 'specimen'): 
    fn = 'results/main/cmipb_datasets/2021BD_{}.csv'.format(metatable)
    df = pd.read_table(fn, sep=',')
    twentyone_data[metatable] = df
    
subjects = twentyone_data['subject']
specimen = twentyone_data['specimen']
master_meta = subjects.merge(specimen, on='subject_id')
master_meta = master_meta[['subject_id',
                           'specimen_id',
                           'infancy_vac',
                           'biological_sex',
                           'year_of_birth',
                           'date_of_boost',
                           'actual_day_relative_to_boost',
                           'planned_day_relative_to_boost',
                           'ethnicity',
                           'race',
                           'dataset',
                           'specimen_type',
                           'visit']]
twentyone_data['master_meta'] = master_meta

In [139]:
for i, longname in enumerate(longnames): 
    fn = 'results/main/cmipb_datasets/2021BD_{}.csv'.format(longname)
    df = pd.read_table(fn, sep=',')
    
    if assays[i] == 'rnaseq':
        df.loc[:, 'ensembl_gene_id'] = df.loc[:, 'versioned_ensembl_gene_id'].str.replace('\.[0-9]+', '')
        df = df.pivot(index='specimen_id', columns='ensembl_gene_id', values='tpm')
        df = master_meta.merge(df, on='specimen_id')
        
    elif assays[i] == 'cytof':
        df = df.pivot(index='specimen_id', columns='cell_type_name', values='percent_live_cell')
        df = master_meta.merge(df, on='specimen_id')
        
    else:
        df = df.pivot(index='specimen_id', columns='uniprot_id', values='protein_expression')
        df = master_meta.merge(df, on='specimen_id')        
    twentyone_data[assays[i]] = df

In [155]:
for assay, df in twentyone_data.items():
    print(assay, df.subject_id.nunique())

subject 36
specimen 36
master_meta 36
cytof 33
olink 36
rnaseq 28

In [180]:
twentyone_data.keys()

dict_keys(['subject', 'specimen', 'master_meta', 'cytof', 'olink', 'rnaseq'])

In [181]:
twentyone_data['cytof']

,subject_id,specimen_id,infancy_vac,biological_sex,year_of_birth,date_of_boost,actual_day_relative_to_boost,planned_day_relative_to_boost,ethnicity,race,...,TcmCD4,TcmCD8,TemCD4,TemCD8,TemraCD4,TemraCD8,cDC1,cDC2,non-pDCs,pDC
0,63,483,wP,Female,1995-01-01,2018-11-26,0,0,Not Hispanic or Latino,White,...,8.73,1.08,2.10,1.78,0.100,2.44,0.023000,0.39,0.54,0.610
1,64,490,wP,Male,1993-01-01,2018-11-26,0,0,Not Hispanic or Latino,Asian,...,3.99,0.37,6.50,6.56,5.360,15.10,0.019000,0.52,0.66,0.055
2,65,498,wP,Male,1990-01-01,2018-12-03,0,0,Not Hispanic or Latino,White,...,16.50,0.75,2.53,2.35,0.035,0.66,0.018000,0.73,1.01,0.650
3,66,506,wP,Female,1976-01-01,2018-12-03,0,0,Not Hispanic or Latino,Black or African American,...,19.40,8.12,6.20,5.02,1.250,2.47,0.013000,0.74,1.03,0.320
4,67,513,wP,Female,1972-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,13.90,0.94,2.55,1.25,0.180,0.72,0.007820,0.88,1.06,0.540
5,68,521,wP,Male,1972-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,17.00,1.02,2.52,1.60,0.140,1.09,0.010000,0.32,0.39,0.200
6,69,529,wP,Female,1990-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,16.70,1.26,6.38,1.93,0.520,0.90,0.002160,0.45,0.79,0.620
7,70,537,aP,Male,1998-01-01,2019-01-28,0,0,Not Hispanic or Latino,American Indian/Alaska Native,...,NaN,NaN,NaN,NaN,NaN,NaN,0.015000,0.78,0.96,0.650
8,71,545,aP,Female,1998-01-01,2019-01-28,0,0,Not Hispanic or Latino,White,...,11.60,1.12,2.76,1.32,0.092,0.86,0.003730,0.36,0.56,0.440
9,72,553,wP,Female,1991-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,5.34,0.69,3.02,4.76,0.100,3.02,0.002160,0.26,0.66,0.830
10,73,561,wP,Female,1995-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,8.73,0.71,2.76,1.59,0.290,2.19,0.006040,0.30,0.54,0.570
11,74,568,wP,Female,1995-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,6.82,1.05,2.32,3.28,0.027,0.82,0.019000,0.80,1.01,0.930
12,76,584,aP,Female,1998-01-01,2019-02-25,0,0,Not Hispanic or Latino,Asian,...,8.06,1.28,2.56,2.49,0.130,4.83,0.012000,0.53,0.61,0.170
13,77,592,wP,Male,1988-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,6.44,1.24,2.51,3.77,0.130,1.76,0.040000,0.99,1.26,0.800
14,78,600,wP,Female,1993-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,4.03,1.17,2.93,2.38,0.610,8.90,0.012000,0.43,0.62,1.230
15,79,607,wP,Male,1987-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,6.61,1.21,1.66,2.28,0.072,0.65,0.004850,0.36,0.47,0.360
16,80,615,wP,Female,1992-01-01,2019-03-18,0,0,Not Hispanic or Latino,Asian,...,2.20,0.35,1.35,3.51,0.100,1.28,0.020000,0.73,0.99,0.470
17,81,622,wP,Male,1993-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,2.23,0.93,2.01,3.76,0.260,9.73,0.039000,1.00,1.75,0.830
18,82,629,aP,Female,1998-01-01,2019-03-18,0,0,Not Hispanic or Latino,More Than One Race,...,8.73,0.66,6.60,2.24,0.340,2.52,0.023000,0.60,0.79,0.490
19,83,635,aP,Female,1999-01-01,2019-04-08,0,0,Not Hispanic or Latino,White,...,3.51,0.19,4.32,0.95,0.840,1.86,0.007920,0.75,0.98,1.330
20,84,642,aP,Female,1997-01-01,2019-04-08,0,0,Not Hispanic or Latino,More Than One Race,...,11.20,0.54,3.94,1.21,1.390,5.74,0.000415,0.45,0.82,0.820
21,85,649,aP,Female,2000-01-01,2019-04-29,0,0,Hispanic or Latino,White,...,8.47,0.90,4.55,4.45,0.096,2.63,0.002790,0.42,0.63,0.410
22,86,656,aP,Female,1998-01-01,2019-04-29,0,0,Not Hispanic or Latino,Asian,...,7.40,0.95,3.52,2.51,0.081,1.00,0.002360,0.39,0.74,0.200
23,87,663,aP,Male,2000-01-01,2019-04-29,0,0,Not Hispanic or Latino,Asian,...,6.50,0.42,1.15,1.08,0.039,0.84,0.027000,0.77,1.17,0.760
24,88,668,aP,Male,2000-01-01,2019-04-29,0,0,Not Hispanic or Latino,Asian,...,5.70,0.61,1.69,1.93,0.110,1.37,0.001860,0.38,0.85,0.410
25,89,673,aP,Female,1997-01-01,2019-06-03,0,0,Not Hispanic or Latino,Asian,...,7.15,0.69,2.88,2.50,0.094,2.06,0.001480,0.40,0.66,0.750
26,90,680,aP,Female,1999-01-01,2019-06-03,0,0,Not Hispanic or Latino,Asian,...,12.70,1.06,2.89,1.41,0.300,1.62,0.039000,0.60,0.81,0.440
27,91,686,aP,Male,1998-01-01,2019-06-03,0,0,Unknown,Unknown or Not Reported,...,3.41,0.44,2.82,1.27,0.280,3.94,0.018000,0.78,1.08,1.240
28,92,693,aP,Female,2000-01-01,2019-06-24,0,0,Hispanic or Latino,White,...,2.77,0.72,2.01,1.34,0.100,2.48,0.016000,0.33,0.58,0.450
29,93,700,aP,Female,1996-01-01,2019-06-24,0,0,Not Hispanic or Latino,More Than One Race,...,5.75,0.69,1.78,0.81,0.220,4.07,0.011000,0.40,0.74,0.940
30,94,707,aP,Male,1999-01-01,2019-06-24,0,0,Not Hispanic or Latino,Unknown or Not Reported,...,5.05,0.75,2.29,1.39,0.160,1.89,0.005720,0.43,0.77,0.910
31,95,714,aP,Female,1998-01-01,2019-06-24,0,0,Hispanic or Latino,Unknown or Not Reported,...,4.78,0.43,2.64,0.91,0.120,5.90,0.008770,0.54,0.80,0.560
32,96,721,aP,Male,2000-01-01,2019-06-24,0,0,Hispanic or Latino,Unknown or Not Reported,...,3.33,0.45,2.47,1.80,0.085,1.99,0.035000,0.94,1.27,0.300

In [182]:
twentyone_data['olink']

,subject_id,specimen_id,infancy_vac,biological_sex,year_of_birth,date_of_boost,actual_day_relative_to_boost,planned_day_relative_to_boost,ethnicity,race,...,Q07325,Q14116,Q14213,Q16552,Q8NEV9,Q969D9,Q96PD4,Q99616,Q99731,Q9P0M4
0,61,468,wP,Female,1987-01-01,2019-04-08,0,0,Not Hispanic or Latino,Unknown or Not Reported,...,109.28744,154.02999,4.77671,1.49907,4.77671,0.10310,0.78253,144.83908,100.86732,12.49224
1,62,475,wP,Female,1993-01-01,2018-11-26,0,0,Not Hispanic or Latino,Asian,...,20.41694,154.10515,3.17013,0.22101,3.17013,0.03151,NaN,107.41612,94.72261,12.22788
2,63,483,wP,Female,1995-01-01,2018-11-26,0,0,Not Hispanic or Latino,White,...,33.14306,108.42327,1.91507,0.04520,1.91507,NaN,0.14084,235.02449,209.67097,8.49530
3,64,490,wP,Male,1993-01-01,2018-11-26,0,0,Not Hispanic or Latino,Asian,...,57.08486,156.50062,7.37701,1.35490,7.37701,0.02532,0.22131,220.31805,78.39164,15.73083
4,65,498,wP,Male,1990-01-01,2018-12-03,0,0,Not Hispanic or Latino,White,...,56.20225,339.68834,1.33409,0.48632,1.33409,0.19344,0.18762,624.05554,169.17528,9.39019
5,66,506,wP,Female,1976-01-01,2018-12-03,0,0,Not Hispanic or Latino,Black or African American,...,46.38606,240.91254,4.33343,1.22580,4.33343,0.08109,0.64337,93.28874,115.41953,13.27354
6,67,513,wP,Female,1972-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,48.47396,291.67923,6.72979,0.13570,6.72979,0.04513,0.04635,287.39899,64.25795,9.09793
7,68,521,wP,Male,1972-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,66.22836,265.42014,3.44553,0.32062,3.44553,0.03812,0.99041,606.31259,107.48543,9.71370
8,69,529,wP,Female,1990-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,72.72014,228.13380,3.24353,0.82289,3.24353,0.00371,0.40881,283.82330,95.59609,14.60257
9,70,537,aP,Male,1998-01-01,2019-01-28,0,0,Not Hispanic or Latino,American Indian/Alaska Native,...,34.58776,195.93473,3.82001,4.35243,3.82001,0.14826,0.61575,474.79616,69.45457,22.08533
10,71,545,aP,Female,1998-01-01,2019-01-28,0,0,Not Hispanic or Latino,White,...,63.65678,220.81417,6.02432,0.23832,6.02432,0.05380,0.63089,291.62784,145.57996,12.92899
11,72,553,wP,Female,1991-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,41.70210,153.92928,3.48984,0.56927,3.48984,0.14914,0.78414,445.29375,82.25982,6.50071
12,73,561,wP,Female,1995-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,36.71114,157.33451,3.45409,0.68823,3.45409,0.04358,0.22240,176.80358,104.55885,15.55668
13,74,568,wP,Female,1995-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,42.31552,250.90693,3.41674,0.26865,3.41674,NaN,0.12261,549.31551,95.89666,11.39359
14,75,576,aP,Female,1998-01-01,2019-02-25,0,0,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,55.79688,182.99845,8.64783,0.18963,8.64783,0.21151,0.57991,156.63742,140.56611,10.48078
15,76,584,aP,Female,1998-01-01,2019-02-25,0,0,Not Hispanic or Latino,Asian,...,36.48048,338.43083,5.83656,0.54020,5.83656,0.02591,0.54722,110.50371,118.51445,10.88902
16,77,592,wP,Male,1988-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,56.13918,232.44278,3.81742,2.39976,3.81742,0.05072,0.11820,648.70069,129.47293,17.64084
17,78,600,wP,Female,1993-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,113.03926,345.46676,6.42837,0.47891,6.42837,0.04342,0.71071,597.55369,163.28645,21.35225
18,79,607,wP,Male,1987-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,50.12049,314.70789,5.77781,0.21487,5.77781,0.13116,0.07450,438.28332,90.22491,19.33593
19,80,615,wP,Female,1992-01-01,2019-03-18,0,0,Not Hispanic or Latino,Asian,...,38.81182,209.31177,9.54815,0.13548,9.54815,1.84264,0.78189,307.14531,282.03484,18.28277
20,81,622,wP,Male,1993-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,37.55121,179.17288,2.22763,0.23002,2.22763,0.01101,0.37026,401.89949,106.64226,22.99987
21,82,629,aP,Female,1998-01-01,2019-03-18,0,0,Not Hispanic or Latino,More Than One Race,...,101.81209,276.04020,7.27682,1.09251,7.27682,0.21348,0.39038,300.12846,309.76934,33.25000
22,83,635,aP,Female,1999-01-01,2019-04-08,0,0,Not Hispanic or Latino,White,...,42.23125,1039.87241,8.51896,0.79454,8.51896,0.14030,2.26284,516.53578,1369.95206,13.87263
23,84,642,aP,Female,1997-01-01,2019-04-08,0,0,Not Hispanic or Latino,More Than One Race,...,42.54251,161.67779,4.67879,0.67031,4.67879,0.01694,0.43648,391.97767,154.93161,19.95278
24,85,649,aP,Female,2000-01-01,2019-04-29,0,0,Hispanic or Latino,White,...,42.88636,206.59473,4.68884,0.61094,4.68884,0.16092,0.39403,295.24567,123.43881,16.98620
25,86,656,aP,Female,1998-01-01,2019-04-29,0,0,Not Hispanic or Latino,Asian,...,33.27698,244.18676,6.38945,0.25671,6.38945,0.05485,2.62975,100.61886,90.57540,11.34215
26,87,663,aP,Male,2000-01-01,2019-04-29,0,0,Not Hispanic or Latino,Asian,...,53.94742,177.28823,5.96456,0.49338,5.96456,0.06329,0.79166,189.18215,96.08505,13.26980
27,88,668,aP,Male,2000-01-01,2019-04-29,0,0,Not Hispanic or Latino,Asian,...,36.38573,210.13166,6.25871,0.35001,6.25871,0.19480,0.72402,195.83403,136.12559,11.47438
28,89,673,aP,Female,1997-01-01,2019-06-03,0,0,Not Hispanic or Latino,Asian,...,78.61131,162.43617,7.38580,1.45186,7.38580,0.03340,1.21937,92.32478,126.81358,23.59060
29,90,680,aP,Female,1999-01-01,2019-06-03,0,0,Not Hispanic or Latino,Asian,...,74.11319,196.54113,7.32195,2.33939,7.32195,0.28061,0.78693,247.70687,105.98134,31.90587
30,91,686,aP,Male,1998-01-01,2019-06-03,0,0,Unknown,Unknown or Not Reported,...,58.93050,125.69167,6.64130,0.62057,6.64130,0.10654,0.28694,431.85613,121.06295,13.48227
31,92,693,aP,Female,2000-01-01,2019-06-24,0,0,Hispanic or Latino,White,...,71.72207,135.83942,2.93610,0.58112,2.93610,0.33379,0.25472,274.72479,79.36819,9.82303
32,93,700,aP,Female,1996-01-01,2019-06-24,0,0,Not Hispanic or Latino,More Than One Race,...,75.27139,267.16750,1.39116,0.52265,1.39116,0.13271,0.74377,234.91394,119.29151,11.88191
33,94,707,aP,Male,1999-01-01,2019-06-24,0,0,Not Hispanic or Latino,Unknown or Not Reported,...,40.04879,197.46171,5.61119,0.27336,5.61119,NaN,0.19841,196.59574,118.16835,21.49705
34,95,714,aP,Female,1998-01-01,2019-06-24,0,0,Hispanic or Latino,Unknown or Not Reported,...,49.30556,258.29362,0.81745,0.39372,0.81745,0.03504,0.32730,499.46462,124.94525,11.05551
35,96,721,aP,Male,2000-01-01,2019-06-24,0,0,Hispanic or Latino,Unknown or Not Reported,...,45.13798,180.63554,2.72092,0.17130,2.72092,0.06790,0.05293,470.10334,109.41269,6.58515

In [183]:
twentyone_data['rnaseq']

,subject_id,specimen_id,infancy_vac,biological_sex,year_of_birth,date_of_boost,actual_day_relative_to_boost,planned_day_relative_to_boost,ethnicity,race,...,ENSG00000284739,ENSG00000284740,ENSG00000284741,ENSG00000284742,ENSG00000284743,ENSG00000284744,ENSG00000284745,ENSG00000284746,ENSG00000284747,ENSG00000284748
0,61,468,wP,Female,1987-01-01,2019-04-08,0,0,Not Hispanic or Latino,Unknown or Not Reported,...,0.0,0.738,0.0,0.0,0.0,0.000,0.0,0.0,1.578,0.122
1,62,475,wP,Female,1993-01-01,2018-11-26,0,0,Not Hispanic or Latino,Asian,...,0.0,1.340,0.0,0.0,0.0,0.000,0.0,0.0,0.645,0.000
2,63,483,wP,Female,1995-01-01,2018-11-26,0,0,Not Hispanic or Latino,White,...,0.0,2.425,0.0,0.0,0.0,0.000,0.0,0.0,1.069,0.101
3,64,490,wP,Male,1993-01-01,2018-11-26,0,0,Not Hispanic or Latino,Asian,...,0.0,1.025,0.0,0.0,0.0,0.000,0.0,0.0,0.876,0.000
4,65,498,wP,Male,1990-01-01,2018-12-03,0,0,Not Hispanic or Latino,White,...,0.0,2.272,0.0,0.0,0.0,0.000,0.0,0.0,0.947,0.000
5,66,506,wP,Female,1976-01-01,2018-12-03,0,0,Not Hispanic or Latino,Black or African American,...,0.0,0.977,0.0,0.0,0.0,0.000,0.0,0.0,3.135,0.122
6,67,513,wP,Female,1972-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,0.0,0.608,0.0,0.0,0.0,0.406,0.0,0.0,1.170,0.000
7,68,521,wP,Male,1972-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,0.0,1.653,0.0,0.0,0.0,0.000,0.0,0.0,1.237,0.000
8,69,529,wP,Female,1990-01-01,2019-01-28,0,0,Hispanic or Latino,White,...,0.0,2.504,0.0,0.0,0.0,0.000,0.0,0.0,0.876,0.000
9,70,537,aP,Male,1998-01-01,2019-01-28,0,0,Not Hispanic or Latino,American Indian/Alaska Native,...,0.0,2.345,0.0,0.0,0.0,0.000,0.0,0.0,1.598,0.000
10,71,545,aP,Female,1998-01-01,2019-01-28,0,0,Not Hispanic or Latino,White,...,0.0,2.649,0.0,0.0,0.0,0.000,0.0,0.0,0.927,0.000
11,72,553,wP,Female,1991-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,0.0,1.789,0.0,0.0,0.0,0.000,0.0,0.0,0.451,0.000
12,73,561,wP,Female,1995-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,0.0,0.794,0.0,0.0,0.0,0.000,0.0,0.0,1.527,0.000
13,74,568,wP,Female,1995-01-01,2019-02-25,0,0,Not Hispanic or Latino,White,...,0.0,0.264,0.0,0.0,0.0,0.000,0.0,0.0,1.015,0.131
14,75,576,aP,Female,1998-01-01,2019-02-25,0,0,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,0.0,0.611,0.0,0.0,0.0,0.000,0.0,0.0,2.450,0.000
15,76,584,aP,Female,1998-01-01,2019-02-25,0,0,Not Hispanic or Latino,Asian,...,0.0,0.286,0.0,0.0,0.0,0.000,0.0,0.0,0.504,0.000
16,77,592,wP,Male,1988-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,0.0,2.000,0.0,0.0,0.0,0.000,0.0,0.0,1.237,0.000
17,78,600,wP,Female,1993-01-01,2019-03-18,0,0,Not Hispanic or Latino,White,...,0.0,1.198,0.0,0.0,0.0,0.000,0.0,0.0,1.152,0.000
18,83,635,aP,Female,1999-01-01,2019-04-08,0,0,Not Hispanic or Latino,White,...,0.0,2.430,0.0,0.0,0.0,0.000,0.0,0.0,1.364,0.151
19,88,668,aP,Male,2000-01-01,2019-04-29,0,0,Not Hispanic or Latino,Asian,...,0.0,2.939,0.0,0.0,0.0,0.000,0.0,0.0,0.689,0.000
20,89,673,aP,Female,1997-01-01,2019-06-03,0,0,Not Hispanic or Latino,Asian,...,0.0,0.483,0.0,0.0,0.0,0.000,0.0,0.0,1.007,0.000
21,90,680,aP,Female,1999-01-01,2019-06-03,0,0,Not Hispanic or Latino,Asian,...,0.0,0.578,0.0,0.0,0.0,0.000,0.0,0.0,1.112,0.000
22,91,686,aP,Male,1998-01-01,2019-06-03,0,0,Unknown,Unknown or Not Reported,...,0.0,0.477,0.0,0.0,0.0,0.000,0.0,0.0,1.414,0.000
23,92,693,aP,Female,2000-01-01,2019-06-24,0,0,Hispanic or Latino,White,...,0.0,1.222,0.0,0.0,0.0,0.163,0.0,0.0,1.019,0.000
24,93,700,aP,Female,1996-01-01,2019-06-24,0,0,Not Hispanic or Latino,More Than One Race,...,0.0,1.763,0.0,0.0,0.0,0.000,0.0,0.0,1.193,0.000
25,94,707,aP,Male,1999-01-01,2019-06-24,0,0,Not Hispanic or Latino,Unknown or Not Reported,...,0.0,1.690,0.0,0.0,0.0,0.000,0.0,0.0,1.247,0.336
26,95,714,aP,Female,1998-01-01,2019-06-24,0,0,Hispanic or Latino,Unknown or Not Reported,...,0.0,0.989,0.0,0.0,0.0,0.000,0.0,0.0,1.190,0.000
27,96,721,aP,Male,2000-01-01,2019-06-24,0,0,Hispanic or Latino,Unknown or Not Reported,...,0.0,0.608,0.0,0.0,0.0,0.000,0.0,0.0,0.585,0.151

In [156]:
########################################################################
# Load the 2020 data ###############################################
########################################################################

In [141]:
twenty_data = {}

# get meta master table
for metatable in ('subject', 'specimen'): 
    fn = 'results/main/cmipb_datasets/2020LD_{}.csv'.format(metatable)
    df = pd.read_table(fn, sep=',')
    twenty_data[metatable] = df
    
subjects = twenty_data['subject']
specimen = twenty_data['specimen']
master_meta = subjects.merge(specimen, on='subject_id')
master_meta = master_meta[['subject_id',
                           'specimen_id',
                           'infancy_vac',
                           'biological_sex',
                           'year_of_birth',
                           'date_of_boost',
                           'actual_day_relative_to_boost',
                           'planned_day_relative_to_boost',
                           'ethnicity',
                           'race',
                           'dataset',
                           'specimen_type',
                           'visit']]
twenty_data['master_meta'] = master_meta

In [142]:
for i, longname in enumerate(longnames): 
    fn = 'results/main/cmipb_datasets/2020LD_{}.csv'.format(longname)
    df = pd.read_table(fn, sep=',')
    
    if assays[i] == 'rnaseq':
        df.loc[:, 'ensembl_gene_id'] = df.loc[:, 'versioned_ensembl_gene_id'].str.replace('\.[0-9]+', '')
        df = df.pivot(index='specimen_id', columns='ensembl_gene_id', values='tpm')
        df = master_meta.merge(df, on='specimen_id')
        
    elif assays[i] == 'cytof':
        df = df.pivot(index='specimen_id', columns='cell_type_name', values='percent_live_cell')
        df = master_meta.merge(df, on='specimen_id')
        
    else:
        # Still getting duplicate specimens? 
        df = df[df['unit'] == "Normalized Protein eXpression"]
        df = df[df['quality_control'] == 'Pass']
        df = df[df['protein_expression'] > df['lower_limit_of_quantitation']]
        df = df.pivot(index='specimen_id', columns='uniprot_id', values='protein_expression')
        df = master_meta.merge(df, on='specimen_id')        
    twenty_data[assays[i]] = df

In [153]:
for assay, df in twenty_data.items():
    print(assay, df.subject_id.nunique())

subject 60
specimen 60
master_meta 60
cytof 22
olink 18
rnaseq 38

In [173]:
summary21 = []
for assay, df in twentyone_data.items():
    summary21.append([assay, df.subject_id.nunique()])

summary20 = []
for assay, df in twenty_data.items():
    summary20.append([df.subject_id.nunique()])

summary = pd.concat([pd.DataFrame(summary21), pd.DataFrame(summary20)], axis=1)
summary.columns = ('table', 'nsamples21', 'nsamples20')
summary = summary[['table', 'nsamples20', 'nsamples21']]

In [174]:
summary

         table  nsamples20  nsamples21
0      subject          60          36
1     specimen          60          36
2  master_meta          60          36
3        cytof          22          33
4        olink          18          36
5       rnaseq          38          28

In [184]:
twenty_data['cytof']

,subject_id,specimen_id,infancy_vac,biological_sex,year_of_birth,date_of_boost,actual_day_relative_to_boost,planned_day_relative_to_boost,ethnicity,race,...,TemCD4,TemCD8,TemraCD4,TemraCD8,Tregs,cDC1,cDC2,mDC,non-pDCs,pDC
0,2,11,wP,Female,1968-01-01,2019-01-28,1,0,Not Hispanic or Latino,White,...,5.000000,3.450000,0.140000,0.820000,NaN,0.001800,0.46,NaN,0.60,0.190000
1,2,12,wP,Female,1968-01-01,2019-01-28,1,1,Not Hispanic or Latino,White,...,4.220000,3.190000,0.540000,0.710000,NaN,0.000690,0.57,NaN,0.78,0.320000
2,2,13,wP,Female,1968-01-01,2019-01-28,3,3,Not Hispanic or Latino,White,...,3.920000,3.480000,0.690000,0.930000,NaN,0.001050,0.44,NaN,0.63,0.300000
3,2,14,wP,Female,1968-01-01,2019-01-28,7,7,Not Hispanic or Latino,White,...,4.600000,2.770000,0.470000,0.640000,NaN,0.000116,0.44,NaN,0.68,0.290000
4,2,15,wP,Female,1968-01-01,2019-01-28,14,14,Not Hispanic or Latino,White,...,3.780000,3.080000,0.150000,0.510000,NaN,0.002240,0.50,NaN,2.30,0.290000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,55,419,aP,Female,1997-01-01,2017-01-17,-8,0,Not Hispanic or Latino,Asian,...,5.845087,2.810857,0.090346,0.783831,0.081312,NaN,NaN,0.736322,NaN,0.724950
106,55,420,aP,Female,1997-01-01,2017-01-17,1,1,Not Hispanic or Latino,Asian,...,6.222055,0.557529,0.798852,0.086226,0.262640,NaN,NaN,0.767286,NaN,0.498770
107,55,421,aP,Female,1997-01-01,2017-01-17,7,3,Not Hispanic or Latino,Asian,...,5.267592,2.750652,0.000000,0.582286,0.284688,NaN,NaN,0.598523,NaN,0.566980
108,55,422,aP,Female,1997-01-01,2017-01-17,7,7,Not Hispanic or Latino,Asian,...,6.235207,2.588152,0.066231,0.537236,0.304636,NaN,NaN,0.704396,NaN,0.532750
109,55,423,aP,Female,1997-01-01,2017-01-17,14,14,Not Hispanic or Latino,Asian,...,7.765109,2.213039,0.166686,1.090901,0.245908,NaN,NaN,0.799400,NaN,0.445692

In [185]:
twenty_data['olink']

,subject_id,specimen_id,infancy_vac,biological_sex,year_of_birth,date_of_boost,actual_day_relative_to_boost,planned_day_relative_to_boost,ethnicity,race,...,Q9UMR7,Q9UN19,Q9UNE0,Q9UQQ2,Q9UQV4,Q9Y286,Q9Y2J8,Q9Y3P8,Q9Y5K6,Q9Y653
0,4,27,wP,Male,1988-01-01,2016-08-29,-7,0,Not Hispanic or Latino,Asian,...,4.74599,NaN,2.57166,3.05939,3.89783,3.26003,NaN,3.22780,4.08113,0.83195
1,4,29,wP,Male,1988-01-01,2016-08-29,1,1,Not Hispanic or Latino,Asian,...,4.80714,2.19070,3.60684,3.43519,3.85207,3.54817,NaN,3.29366,4.66547,NaN
2,4,30,wP,Male,1988-01-01,2016-08-29,3,3,Not Hispanic or Latino,Asian,...,4.85797,1.58475,2.84485,2.89795,3.95568,3.63367,NaN,2.78537,4.04778,NaN
3,4,31,wP,Male,1988-01-01,2016-08-29,8,7,Not Hispanic or Latino,Asian,...,4.60806,1.54995,2.32716,2.71059,3.74687,3.37293,NaN,3.04275,3.66745,NaN
4,4,32,wP,Male,1988-01-01,2016-08-29,14,14,Not Hispanic or Latino,Asian,...,4.53035,NaN,2.38944,2.50667,3.67100,3.46749,NaN,3.36227,3.78405,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,52,397,aP,Male,1998-01-01,2017-01-03,-34,0,Not Hispanic or Latino,More Than One Race,...,5.18060,2.11278,3.08292,3.58958,4.05736,3.58235,NaN,2.91209,4.20188,NaN
86,52,398,aP,Male,1998-01-01,2017-01-03,1,1,Not Hispanic or Latino,More Than One Race,...,5.04124,NaN,2.85008,2.63700,4.06376,2.98766,NaN,3.14567,4.07638,NaN
87,52,399,aP,Male,1998-01-01,2017-01-03,3,3,Not Hispanic or Latino,More Than One Race,...,5.05094,1.69936,3.23156,3.12789,4.13642,3.26902,NaN,3.21674,4.43488,NaN
88,52,400,aP,Male,1998-01-01,2017-01-03,8,7,Not Hispanic or Latino,More Than One Race,...,4.94167,NaN,2.28550,2.45255,3.88129,3.20957,NaN,3.46613,3.51185,NaN
89,52,401,aP,Male,1998-01-01,2017-01-03,14,14,Not Hispanic or Latino,More Than One Race,...,5.25293,1.62640,3.20665,3.29402,4.23703,3.26440,NaN,3.05034,4.24601,NaN

In [186]:
twenty_data['rnaseq']

,subject_id,specimen_id,infancy_vac,biological_sex,year_of_birth,date_of_boost,actual_day_relative_to_boost,planned_day_relative_to_boost,ethnicity,race,...,ENSG00000284739,ENSG00000284740,ENSG00000284741,ENSG00000284742,ENSG00000284743,ENSG00000284744,ENSG00000284745,ENSG00000284746,ENSG00000284747,ENSG00000284748
0,1,1,wP,Female,1986-01-01,2016-09-12,-3,0,Not Hispanic or Latino,White,...,0.0,1.219,0.0,0.0,0.0,0.00,0.0,0.0,1.173,0.000
1,1,3,wP,Female,1986-01-01,2016-09-12,1,1,Not Hispanic or Latino,White,...,0.0,0.273,0.0,0.0,0.0,0.00,0.0,0.0,0.657,0.000
2,1,4,wP,Female,1986-01-01,2016-09-12,3,3,Not Hispanic or Latino,White,...,0.0,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.913,0.000
3,1,5,wP,Female,1986-01-01,2016-09-12,7,7,Not Hispanic or Latino,White,...,0.0,0.473,0.0,0.0,0.0,0.00,0.0,0.0,0.947,0.000
4,1,6,wP,Female,1986-01-01,2016-09-12,11,14,Not Hispanic or Latino,White,...,0.0,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.783,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,53,405,aP,Female,1998-01-01,2017-01-03,-28,0,Hispanic or Latino,Unknown or Not Reported,...,0.0,0.449,0.0,0.0,0.0,0.15,0.0,0.0,0.755,0.000
186,53,406,aP,Female,1998-01-01,2017-01-03,1,1,Hispanic or Latino,Unknown or Not Reported,...,0.0,0.405,0.0,0.0,0.0,0.00,0.0,0.0,1.071,0.101
187,53,407,aP,Female,1998-01-01,2017-01-03,3,3,Hispanic or Latino,Unknown or Not Reported,...,0.0,0.602,0.0,0.0,0.0,0.00,0.0,0.0,0.901,0.000
188,53,408,aP,Female,1998-01-01,2017-01-03,8,7,Hispanic or Latino,Unknown or Not Reported,...,0.0,0.404,0.0,0.0,0.0,0.00,0.0,0.0,0.486,0.000
189,53,409,aP,Female,1998-01-01,2017-01-03,14,14,Hispanic or Latino,Unknown or Not Reported,...,0.0,0.676,0.0,0.0,0.0,0.00,0.0,0.0,1.085,0.000

In [150]:
fn = 'results/main/cmipb_datasets/2020LD_{}.csv'.format('olink_prot_exp')
df = pd.read_table(fn, sep=',')

In [152]:
df.unit.unique()

array(['Normalized Protein eXpression', 'PG/ML'], dtype=object)